### ISSUE TITLE
You should take the sqrt of your weights

### ISSUE THREAD

**Issue by prittjam** [JAAdrian/MatlabRobustNonlinLsq#1]
The weighting should be rooted since lsqnonlin will square the weighted residual, and thus square the influence function. E.g., see https://members.loria.fr/moberger/Enseignement/Master2/Documents/ZhangIVC-97-01.pdf

**Comment by JAAdrian** [comment]
Nice catch, thank you!  
I will fix this ASAP

**Comment by prittjam** [comment]
Also I think you need to divide the influence function by the residual. See Eq. 25, https://members.loria.fr/moberger/Enseignement/Master2/Documents/ZhangIVC-97-01.pdf. This will allow you to use standard lsqnonlin to robustly fit a function.

**Comment by JAAdrian** [comment]
Could you check [the pull request](https://github.com/JAAdrian/MatlabRobustNonlinLsq/pull/2/files) if this already fixes these issues? I have not incorporated handling the influence function for now since it is more involved.
